# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lukyan/uni/paoo/PAOO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lukyan/uni/paoo/PAOO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukyan/uni/paoo/PAOO/CMakeFiles /home/lukyan/uni/paoo/PAOO//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukyan/uni/paoo/PAOO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named race_lib

# Build rule for target.
race_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 race_lib
.PHONY : race_lib

# fast build rule for target.
race_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/build
.PHONY : race_lib/fast

#=============================================================================
# Target rules for targets named race

# Build rule for target.
race: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 race
.PHONY : race

# fast build rule for target.
race/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race.dir/build.make CMakeFiles/race.dir/build
.PHONY : race/fast

src/aero.o: src/aero.cpp.o
.PHONY : src/aero.o

# target to build an object file
src/aero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/aero.cpp.o
.PHONY : src/aero.cpp.o

src/aero.i: src/aero.cpp.i
.PHONY : src/aero.i

# target to preprocess a source file
src/aero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/aero.cpp.i
.PHONY : src/aero.cpp.i

src/aero.s: src/aero.cpp.s
.PHONY : src/aero.s

# target to generate assembly for a file
src/aero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/aero.cpp.s
.PHONY : src/aero.cpp.s

src/car.o: src/car.cpp.o
.PHONY : src/car.o

# target to build an object file
src/car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/car.cpp.o
.PHONY : src/car.cpp.o

src/car.i: src/car.cpp.i
.PHONY : src/car.i

# target to preprocess a source file
src/car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/car.cpp.i
.PHONY : src/car.cpp.i

src/car.s: src/car.cpp.s
.PHONY : src/car.s

# target to generate assembly for a file
src/car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/car.cpp.s
.PHONY : src/car.cpp.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race.dir/build.make CMakeFiles/race.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race.dir/build.make CMakeFiles/race.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race.dir/build.make CMakeFiles/race.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/person.o: src/person.cpp.o
.PHONY : src/person.o

# target to build an object file
src/person.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/person.cpp.o
.PHONY : src/person.cpp.o

src/person.i: src/person.cpp.i
.PHONY : src/person.i

# target to preprocess a source file
src/person.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/person.cpp.i
.PHONY : src/person.cpp.i

src/person.s: src/person.cpp.s
.PHONY : src/person.s

# target to generate assembly for a file
src/person.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/person.cpp.s
.PHONY : src/person.cpp.s

src/race.o: src/race.cpp.o
.PHONY : src/race.o

# target to build an object file
src/race.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/race.cpp.o
.PHONY : src/race.cpp.o

src/race.i: src/race.cpp.i
.PHONY : src/race.i

# target to preprocess a source file
src/race.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/race.cpp.i
.PHONY : src/race.cpp.i

src/race.s: src/race.cpp.s
.PHONY : src/race.s

# target to generate assembly for a file
src/race.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/race.cpp.s
.PHONY : src/race.cpp.s

src/team.o: src/team.cpp.o
.PHONY : src/team.o

# target to build an object file
src/team.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/team.cpp.o
.PHONY : src/team.cpp.o

src/team.i: src/team.cpp.i
.PHONY : src/team.i

# target to preprocess a source file
src/team.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/team.cpp.i
.PHONY : src/team.cpp.i

src/team.s: src/team.cpp.s
.PHONY : src/team.s

# target to generate assembly for a file
src/team.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/team.cpp.s
.PHONY : src/team.cpp.s

src/tire.o: src/tire.cpp.o
.PHONY : src/tire.o

# target to build an object file
src/tire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/tire.cpp.o
.PHONY : src/tire.cpp.o

src/tire.i: src/tire.cpp.i
.PHONY : src/tire.i

# target to preprocess a source file
src/tire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/tire.cpp.i
.PHONY : src/tire.cpp.i

src/tire.s: src/tire.cpp.s
.PHONY : src/tire.s

# target to generate assembly for a file
src/tire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/race_lib.dir/build.make CMakeFiles/race_lib.dir/src/tire.cpp.s
.PHONY : src/tire.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... race"
	@echo "... race_lib"
	@echo "... src/aero.o"
	@echo "... src/aero.i"
	@echo "... src/aero.s"
	@echo "... src/car.o"
	@echo "... src/car.i"
	@echo "... src/car.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/person.o"
	@echo "... src/person.i"
	@echo "... src/person.s"
	@echo "... src/race.o"
	@echo "... src/race.i"
	@echo "... src/race.s"
	@echo "... src/team.o"
	@echo "... src/team.i"
	@echo "... src/team.s"
	@echo "... src/tire.o"
	@echo "... src/tire.i"
	@echo "... src/tire.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

